digid_eherkenning/urls.py
from django.urls import include, path

# Default URL patterns - you can break this out in the individual modules if preferred.

urlpatterns = [
    path("digid/", include("digid_eherkenning.digid_urls")),
    path("eherkenning/", include("digid_eherkenning.eherkenning_urls")),
    path("metadata/", include("digid_eherkenning.metadata_urls")),
]

digid_eherkenning/forms.py
from django import forms


class SAML2Form(forms.Form):
    SAMLRequest = forms.CharField()
    RelayState = forms.CharField(max_length=80)

digid_eherkenning/mock/idp/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from ...models.digid import MockDigidUser
from ...validators import BSNValidator


class BsnLoginUserModelForm(forms.Form):
    auth_user = forms.ModelChoiceField(
        queryset=MockDigidUser.objects.all(),
        label=_("DigiD mock gebruiker"),
        required=True,
    )

    @property
    def bsn(self):
        return self.cleaned_data["auth_user"].bsn


class BsnLoginTextInputForm(forms.Form):
    auth_bsn = forms.CharField(
        max_length=9,
        label=_("Burgerservicenummer"),
        required=True,
        validators=[BSNValidator()],
    )

    @property
    def bsn(self):
        return self.cleaned_data["auth_bsn"]

digid_eherkenning/mock/idp/views/digid.py
import logging
from urllib.parse import urlencode

from django.http import HttpRequest, HttpResponseBadRequest
from django.urls import reverse
from django.views.generic import FormView, TemplateView

from furl import furl

from digid_eherkenning.mock import conf
from digid_eherkenning.mock.idp.forms import (
    BsnLoginTextInputForm,
    BsnLoginUserModelForm,
)
from digid_eherkenning.models.digid import MockDigidUser
from digid_eherkenning.views.base import get_redirect_url

logger = logging.getLogger(__name__)


class _BaseIDPViewMixin(TemplateView):
    page_title = "DigiD: Inloggen"

    @staticmethod
    def _is_allowed_callback(request: HttpRequest, url: str):
        """
        Determine whether `url` is an allowed callback for the mock IDP.

        The callback URL should be a relative path, or match the host of the mock IDP
        view. If the IDP is served under HTTPS, then the callback URL must also use
        HTTPS.
        """
        return get_redirect_url(
            request,
            url,
            # Unsafe redirects are not uncommon in development settings, but if the IDP
            # is hosted behind TLS, the callbacks should also be secure.
            require_https=request.is_secure(),
        )

    def dispatch(self, request, *args, **kwargs):
        # we pass these variables through the URL instead of dealing with POST and sessions
        self.acs_url = self.request.GET.get("acs")
        self.next_url = self.request.GET.get("next")
        self.cancel_url = self.request.GET.get("cancel") or self.request.GET.get(
            "next", ""
        )

        if not self.acs_url:
            logger.debug("missing 'acs' parameter")
            return HttpResponseBadRequest("missing 'acs' parameter")
        if not self.next_url:
            logger.debug("missing 'next' parameter")
            return HttpResponseBadRequest("missing 'next' parameter")
        if not self.cancel_url:
            logger.debug("missing 'cancel' parameter")
            return HttpResponseBadRequest("missing 'cancel' parameter")

        # The principal use-case is that the mock IDP redirect flow all takes place
        # within the same service. This should generally only be used in development,
        # but out of an abundance of caution, and also to please security scanners, we
        # only allow redirects to the same host that is serving the mock IDP should the
        # IDP be active in world-facing environments (e.g. in acceptance). This behavior
        # can be disabled with the DIGID_MOCK_IDP_VALIDATE_CALLBACK_URLS setting.
        if conf.should_validate_idp_callback_urls():
            if not self._is_allowed_callback(request, self.next_url):
                return HttpResponseBadRequest("'next_url' parameter must be a safe url")

            if not self._is_allowed_callback(request, self.cancel_url):
                return HttpResponseBadRequest(
                    "'cancel_url' parameter must be a safe url"
                )

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        return {
            "app_title": conf.get_app_title(),
            "page_title": self.page_title,
            **super().get_context_data(**kwargs),
        }


class DigiDMockIDPLoginView(_BaseIDPViewMixin):
    """
    Login method choices pages
    """

    template_name = "digid_eherkenning/mock/login.html"
    page_title = "DigiD: Inloggen | Keuze"

    def get_context_data(self, **kwargs):
        params = {
            "acs": self.acs_url,
            "next": self.next_url,
            "cancel": self.cancel_url,
        }
        return {
            "cancel_url": params["cancel"],
            "password_login_url": f"{reverse('digid-mock:bsn')}?{urlencode(params)}",
            **super().get_context_data(**kwargs),
        }


class DigiDMockIDPBSNLoginView(_BaseIDPViewMixin, FormView):
    """
    BSN login page
    """

    template_name = "digid_eherkenning/mock/bsn.html"
    page_title = "DigiD: Inloggen | BSN"

    def get_form_class(self):
        if MockDigidUser.objects.exists():
            return BsnLoginUserModelForm
        else:
            return BsnLoginTextInputForm

    def form_valid(self, form):
        self.bsn = form.bsn
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        params = {
            "acs": self.acs_url,
            "next": self.next_url,
            "cancel": self.cancel_url,
        }
        return {
            "action_url": f"{reverse('digid-mock:bsn')}?{urlencode(params)}",
            "back_url": f"{reverse('digid-mock:login')}?{urlencode(params)}",
            **super().get_context_data(**kwargs),
        }

    def get_success_url(self):
        params = {
            "next": self.next_url,
            "bsn": str(self.bsn),
        }
        success_url = furl(self.acs_url)
        success_url.args.update(params)
        return str(success_url)

digid_eherkenning/mock/views/digid.py
import logging
from urllib.parse import urlencode

from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth.views import LogoutView
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import resolve_url
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import RedirectView

from digid_eherkenning.mock import conf
from digid_eherkenning.views.base import get_redirect_url

logger = logging.getLogger(__name__)


class DigiDLoginMockView(RedirectView):
    """
    mock replacement for digid:login

    we do a simple redirect instead of a form POST like post_binding.html does
    """

    def get_redirect_url(self, *args, **kwargs):
        url = self.request.build_absolute_uri(conf.get_idp_login_url())

        next_url = self.request.GET.get("next") or self.request.build_absolute_uri(
            conf.get_success_url()
        )
        next_url = get_redirect_url(
            self.request, next_url, require_https=self.request.is_secure()
        )
        if not next_url:
            logger.debug("bad 'next' redirect parameter")
            return HttpResponseBadRequest("bad 'next' redirect parameter")

        cancel_url = self.request.GET.get("cancel") or self.request.build_absolute_uri(
            conf.get_cancel_url()
        )
        cancel_url = get_redirect_url(
            self.request, cancel_url, require_https=self.request.is_secure()
        )
        if not cancel_url:
            logger.debug("bad 'cancel' redirect parameter")
            return HttpResponseBadRequest("bad 'cancel' redirect parameter")

        params = {
            "next": next_url,
            "cancel": cancel_url,
            "acs": self.request.build_absolute_uri(reverse("digid:acs")),
        }
        return f"{url}?{urlencode(params)}"


class DigiDAssertionConsumerServiceMockView(View):
    """
    mock replacement for digid:acs
    """

    def get_login_url(self):
        """
        where to go after unsuccessful login
        """
        url = self.request.build_absolute_uri(conf.get_cancel_url())
        url = get_redirect_url(
            self.request, url, require_https=self.request.is_secure()
        )
        if url:
            return url

        return resolve_url(settings.LOGIN_URL)

    def get_success_url(self):
        """
        where to go after successful login
        """
        url = self.request.GET.get("next") or self.request.build_absolute_uri(
            conf.get_success_url()
        )
        url = get_redirect_url(
            self.request, url, require_https=self.request.is_secure()
        )
        return url or resolve_url(settings.LOGIN_REDIRECT_URL)

    def get(self, request):
        user = auth.authenticate(request=request, bsn=request.GET.get("bsn"))
        if user is None:
            message = _(
                "An error occurred in the communication with DigiD. "
                "Please try again later. If this error persists, please "
                "check the website https://www.digid.nl for the latest information."
            )
            messages.error(request, message)
            login_url = self.get_login_url()
            return HttpResponseRedirect(login_url)

        auth.login(request, user)

        return HttpResponseRedirect(self.get_success_url())


class DigiDLogoutMockView(LogoutView):
    # in the future we can render a custom template to emulate Digid logout page
    pass

digid_eherkenning/views.py
from base64 import b64encode

from django.conf import settings
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import resolve_url

# Django 1.11 compatibility
try:
    from django.utils.http import url_has_allowed_host_and_scheme
except ImportError:
    from django.utils.http import is_safe_url as url_has_allowed_host_and_scheme

from django.views.generic.base import TemplateView, View

from saml2 import BINDING_HTTP_ARTIFACT, BINDING_HTTP_POST
from saml2.authn_context import PASSWORDPROTECTEDTRANSPORT, requested_authn_context
from saml2.client_base import IdpUnspecified
from saml2.xmldsig import DIGEST_SHA256, SIG_RSA_SHA256

from .client import Saml2Client
from .forms import SAML2Form


def get_redirect_url(request, redirect_to):
    """
    Make sure the URL we redirect to is safe. HTTPs
    is always required.
    """

    url_is_safe = url_has_allowed_host_and_scheme(
        url=redirect_to, allowed_hosts=[request.get_host(),], require_https=True,
    )
    if url_is_safe:
        return redirect_to

    return ""


class LoginView(TemplateView):
    """
    DigiD - 3.3.2 - Stap 2 Authenticatievraag
    """

    template_name = "digid_eherkenning/post_binding.html"

    def get_relay_state(self):
        """
        TODO: It might be a good idea to sign the relay state.
        But I can't think of a way this could be abused, since
        we re-check the url when processed by the ACS.
        """
        redirect_to = self.request.GET.get("next", "")
        return get_redirect_url(self.request, redirect_to)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        client = Saml2Client()

        response_binding = BINDING_HTTP_ARTIFACT

        # Retrieve the right HTTP POST location from the metadata file.
        try:
            location = client.sso_location(
                "https://was-preprod1.digid.nl/saml/idp/metadata", BINDING_HTTP_POST
            )
        except IdpUnspecified:
            return HttpResponseServerError()

        #
        # nameid_format='' means don't include the NameIDPolicy.
        #
        session_id, request_xml = client.create_authn_request(
            location,
            binding=response_binding,
            nameid_format="",
            sign=True,
            sign_prepare=False,
            sign_alg=SIG_RSA_SHA256,
            digest_alg=DIGEST_SHA256,
            requested_authn_context=requested_authn_context(PASSWORDPROTECTEDTRANSPORT),
        )
        saml_request = b64encode(str(request_xml).encode("utf-8")).decode("utf-8")

        context_data.update(
            {
                "url": location,
                "form": SAML2Form(
                    initial={
                        "SAMLRequest": saml_request,
                        "RelayState": self.get_relay_state(),
                    }
                ),
            }
        )

        return context_data


class AssertionConsumerServiceView(View):
    """
    DigiD - 3.3.3 Stap 5 Artifact
    """

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url(settings.LOGIN_REDIRECT_URL)

    def get_redirect_url(self):
        redirect_to = self.request.GET.get("RelayState")
        return get_redirect_url(self.request, redirect_to)

    def get(self, request):
        user = auth.authenticate(request=request, saml_art=request.GET.get("SAMLart"))
        if user is None:
            raise PermissionDenied("Forbidden")

        auth.login(request, user)

        return HttpResponseRedirect(self.get_redirect_url())

digid_eherkenning/views/base.py
from django.utils.http import url_has_allowed_host_and_scheme


def get_redirect_url(request, redirect_to, require_https=True):
    """
    Make sure the URL we redirect to is safe. HTTPs
    is always required.
    """

    url_is_safe = url_has_allowed_host_and_scheme(
        url=redirect_to,
        allowed_hosts=[
            request.get_host(),
        ],
        require_https=require_https,
    )
    if url_is_safe:
        return redirect_to

    return ""

digid_eherkenning/views/eherkenning.py
from django.conf import settings
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.shortcuts import resolve_url
from django.utils.translation import gettext as _
from django.views.generic.base import TemplateView, View

from ..exceptions import SAML2Error, eHerkenningNoRSINError
from ..forms import SAML2Form
from ..saml2.eherkenning import eHerkenningClient
from .base import get_redirect_url


class eHerkenningLoginView(TemplateView):
    template_name = "digid_eherkenning/post_binding.html"

    def get_relay_state(self):
        """
        TODO: It might be a good idea to sign the relay state.
        But I can't think of a way this could be abused, since
        we re-check the url when processed by the ACS.
        """
        redirect_to = self.request.GET.get("next", "")
        return get_redirect_url(self.request, redirect_to)

    def get_attribute_consuming_service_index(self) -> str | None:
        attribute_consuming_service_index = self.request.GET.get(
            "attr_consuming_service_index"
        )
        return attribute_consuming_service_index

    #
    # TODO: It might be a good idea to change this to a post-verb.
    # I can't think of any relay attack-vectors, but seems like a good
    # idea anyways.
    #
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        client = eHerkenningClient()
        location, parameters = client.create_authn_request(
            self.request,
            attr_consuming_service_index=self.get_attribute_consuming_service_index(),
        )

        context_data.update(
            {
                "url": location,
                "form": SAML2Form(
                    initial={
                        "SAMLRequest": parameters["SAMLRequest"],
                        "RelayState": self.get_relay_state(),
                    }
                ),
            }
        )
        return context_data


class eHerkenningAssertionConsumerServiceView(View):
    login_url = None

    def get_login_url(self):
        url = self.get_redirect_url()
        if url:
            return url

        return resolve_url(settings.LOGIN_URL)

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url(settings.LOGIN_REDIRECT_URL)

    def get_redirect_url(self):
        redirect_to = self.request.GET.get("RelayState")
        return get_redirect_url(self.request, redirect_to)

    def handle_error(self, request, message):
        messages.error(request, message)
        login_url = self.get_login_url()
        return HttpResponseRedirect(login_url)

    def get(self, request):
        try:
            user = auth.authenticate(
                request=request, eherkenning=True, saml_art=request.GET.get("SAMLart")
            )
        except eHerkenningNoRSINError:
            return self.handle_error(
                request,
                _(
                    "No RSIN returned by eHerkenning. Login to eHerkenning did not succeed."
                ),
            )
        except SAML2Error:
            return self.handle_error(
                request, _("Login to eHerkenning did not succeed. Please try again.")
            )

        if user is None:
            return self.handle_error(
                request, _("Login to eHerkenning did not succeed. Please try again.")
            )

        auth.login(request, user)

        return HttpResponseRedirect(self.get_success_url())

digid_eherkenning/templates/digid_eherkenning/mock/base.html
{% load static %}
<!DOCTYPE html>
<html class='no-javascript' lang='nl'>
<head>
    <meta charset='utf-8'/>
    <meta
        content='Met uw persoonlijke DigiD kunt u zich identificeren op websites van de overheid. Zo weten overheidsinstellingen dat ze echt met u te maken hebben.'
        name='description'/>
    <meta content='DigiD, inloggen, aanvragen, activeren, Mijn DigiD' name='keywords'/>
    <meta content='index, follow' name='robots'/>
    <meta content='width=device-width, initial-scale=1' name='viewport'/>
    <meta content='none' name='msapplication-config'/>

    <title>{{ page_title }}</title>

    <link href='{% static 'digid-mock/assets/ro-favicon-wit-0xffffff.png' %}' rel='shortcut icon'/>
    <link rel="stylesheet" media="all" href="{% static 'digid-mock/assets/application.css' %}"/>
    <link rel="stylesheet" media="all" href="{% static 'digid-mock/extra.css' %}"/>
    <script src="{% static 'digid-mock/extra.js' %}"></script>
</head>
<body>
<div class='small window'>
    <div class='content'>
        <header class='header'>
            <div>
                {% block service_menu %}{% endblock %}
                <a class="digidmock-anchor-placeholder">
                    <img alt="Logo Rijksoverheid" class="rijksoverheid-logo" title="Logo Rijksoverheid"
                        src="{% static 'digid-mock/assets/RO_DigiD_Logo_Homepage.svg' %}"/>
                </a>
                <nav class='header-navigation'></nav>
            </div>
            <div style='margin-top: 15px'></div>
        </header>
        <div class='main'>
            <section class='main-content' id='main_content' style='outline: none' tabindex='-1'>
                <div class="heading_with_icon"><img alt="Vignet" class="digid-logo"
                    src="{% static 'digid-mock/assets/digid_eo_rgb.svg' %}"/>
                    <h1 class="h2">
                        <strong>Inloggen bij</strong> <br/> {{ app_title }}
                    </h1>
                </div>

                <div class="digidmock-notification">
                    <strong>Dit is een mockup van de DigiD login flow voor test en demonstratie doeleinden.</strong>
                    <br>
                    Vul niet uw echte DigiD logingegevens in.
                </div>

                {% block body %}{% endblock %}

            </section>
            <div class='bld-footer-ribbon'></div>
        </div>
    </div>
    <footer class='footer'>
        <div class='footer-questions'>
            <h4>Vraag en antwoord</h4>
            <ul class='questions'>
                <li class='questions-item'>
                    <a class='questions-question digidmock-anchor-placeholder'>
                        <i class="icon-3941-delta-links-24px" style="font-size: 75%; color: #282828" aria-hidden='true'
                            aria-label="delta links icoon"></i>
                        Ik ben mijn gebruikersnaam vergeten
                    </a>
                </li>
            </ul>
            <h4>Geen antwoord op uw vraag?</h4>
            <p>
                <a target="_blank" class="digidmock-anchor-placeholder">Bekijk de DigiD website</a> [opent in een
                nieuw venster] of <a target="_blank" class="digidmock-anchor-placeholder">neem contact op</a> [opent
                in een nieuw venster] met de DigiD helpdesk.
            </p>
        </div>

    </footer>
</div>

</body>
</html>

digid_eherkenning/templates/digid_eherkenning/mock/bsn.html
{% extends "digid_eherkenning/mock/base.html" %}

{% block body %}
    <h2 class="orange_heading">Vul hieronder uw Burgerservicenummer in.</h2>

    <form class="remember_login" id="new_authentication" action="{{ action_url }}"
        accept-charset="UTF-8" method="post">
        {% csrf_token %}
        <input name="utf8" type="hidden" value="✓">

        <div class="normal-login" id="normal-login">
            <header class="form__header"></header>

            <fieldset class="form__item" id="username-field">
                <label class="form__item__label" for="authentication_username">Burgerservicenummer</label>

                {% if form.auth_user %}
                    <select class="form__item__field" id="id_auth_user" name="auth_user">
                        {% for mock_bsn_user in form.auth_user %}
                            {{ mock_bsn_user }}
                        {% endfor %}
                    </select>
                {% else %}
                    <input class="form__item__field" spellcheck="false" placeholder=" " type="text" name="{{ form.auth_bsn.name }}" value="{% firstof form.auth_bsn.value '' %}"> 
                {% endif %}

                <ul id="authentication_username__empty" class="form__item__errors digidmock-error {% if form.auth_user.errors or form.auth_bsn.errors %}digidmock-show{% endif %}">
                    <li><strong>Vul een geldig burgerservicenummer in.</strong> <br>Dit is een verplicht
                        veld.
                    </li>
                </ul>
            </fieldset>

            <div class="actions">
                <button name="commit" type="submit" class="actions__right--button primary--button arrow"
                    data-disable-with="Inloggen" id="submit-button" arrow="true" value="Inloggen">
                    Inloggen
                </button>
                <a action="previous" arrow="true" css_type="button" class="actions__left--button arrow"
                    href="{{ back_url }}">Vorige</a>
            </div>
        </div>
    </form>

    <ul class='list-with-arrows'>
        <li id='forgot_password'><a class="digidmock-anchor-placeholder">Wachtwoord
            vergeten?</a></li>
        <li id='request-new-digid'><a class="digidmock-anchor-placeholder">Nog
            geen DigiD? Vraag uw DigiD aan</a></li>
    </ul>
{% endblock %}

digid_eherkenning/templates/digid_eherkenning/mock/login.html
{% extends "digid_eherkenning/mock/base.html" %}

{% block service_menu %}
    <nav class='service-menu'>
        <ul class='service-menu-items'>
            <li>
                <a class="language-menu-item digidmock-anchor-placeholder" data-locale="en">EN</a>
            </li>
            <li>
                <a class="language-menu-item active digidmock-anchor-placeholder" data-locale="nl">NL</a>
            </li>
        </ul>
    </nav>
{% endblock %}


{% block body %}
    <h2 class='orange_heading' id='authentication_heading'>Hoe wilt u inloggen?</h2>

    <div class='authentications'>
        <a class='active app authentication login_tile digidmock-anchor-placeholder'
            id='authentication_type_account_app'>
            <h2>
                <span>Met de DigiD app</span>
                <p class='description'>De makkelijkste manier om veilig in te loggen</p>
            </h2>
            <i class="icon-3941-delta-links-24px" style="float: right" aria-hidden='true'
                aria-label="3941-delta-links- icoon"></i>
        </a>

        <a class='authentication login_tile' href='{{ password_login_url }}'
            id='authentication_type_account_basis'>
            <h2>
                <i class="icon-basis" aria-hidden='true' aria-label="basis icoon"></i>
                <span>Met burgerservicenummer.</span>
                <p class='description'></p>
            </h2>
            <i class="icon-3941-delta-links-24px" style="float: right" aria-hidden='true'
                aria-label="3941-delta-links- icoon"></i>
        </a>
    </div>
    <div class='actions'>
        <form class="button_to" method="get" action="{{ cancel_url }}">
            <button arrow="true" class="actions__left--button arrow" type="submit">Annuleren</button>
        </form>
    </div>
    <ul class='list-with-arrows' style='margin-bottom: 48px;'>
        <li id='request-new-digid'>
            <a class="digidmock-anchor-placeholder">Nog geen DigiD? Vraag uw DigiD aan</a>
        </li>
    </ul>

{% endblock %}